[tool.ruff]
    line-length = 120

[tool.ruff.format]
    quote-style = 'single'

[tool.ruff.lint.isort]
    combine-as-imports = true

[tool.ruff.lint]
    extend-select = ['I']

[tool.pytest]
    testpaths = ['tests']

[tool.pytest.ini_options]
    addopts = '--tb=native'

[tool.logfire]
    project_name = 'Plutus'